package:
  name: pygalle.core.base.klass
  version: 0.1.4
github:
  username: pygalle-io
  repository: pygalle.core.base.klass
workInProgress: true
credits:
  - package:
      name: shortid
      url: https://github.com/corpix/shortid
      license: '[Copyright (c) 2014 Dmitry Moskowski <me@corpix.ru>, MIT License](https://raw.githubusercontent.com/corpix/shortid/master/LICENSE)'
    author:
      name: corpix
      url: https://github.com/corpix/
  - package:
      name: DotMap
      url: https://github.com/drgrib/dotmap
      license: '[Copyright (c) 2015 Chris Redford, MIT License](https://raw.githubusercontent.com/drgrib/dotmap/master/LICENSE.txt)'
    author:
      name: drgrib
      url: https://github.com/drgrib/
copyright:
  year: 2018
  author:
    name: SAS 9 FÃ©vrier
    url: https://9fevrier.com/
example: |
  from pygalle.core.base.klass import PygalleBaseClass

  # Extends the PygalleBaseClass
  class CustomClass(PygalleBaseClass):

      def __init__(self, *args, **kwargs)
        super().__init__(*args, **kwargs)

